### ISSUE TITLE
KiteConnect not working with flask

### ISSUE THREAD

**Issue by shipdcare** [rainmattertech/pykiteconnect#18]
importing kiteconnect statement causes an unknown error that does not enable flask to create a server.

Sample code-

from flask import Flask, render_template, redirect
from kiteconnect import KiteConnect

app = Flask(__name__)

@app.route("/")
@app.route("/app")
def index():
    return "Hello World"

if __name__ == "__main__":
    app.run(debug=True)

**Comment by vividvilla** [comment]
I have tried your example and it seems to be working. Here is my version (there were few errors in your code)
```
from flask import Flask, render_template, redirect
from kiteconnect import KiteConnect

app = Flask(__name__)

@app.route("/")
@app.route("/app")
def index():
        return "Hello World"

if __name__ == "__main__":
        app.run(debug=True, port=6999)
```

**Comment by shipdcare** [comment]
Hi, the script is running without any errors, but the server is not starting. I cannot visit localhost:6999 .

**Comment by vividvilla** [comment]
Its running on my machine. Here is the screenshot.
![screen shot 2017-06-02 at 10 29 49 pm](https://cloud.githubusercontent.com/assets/715529/26736407/87679bf2-47e3-11e7-8cc9-c5dfdcf936d1.png)
